import { PrismaClient, SurveyInstrument } from '@prisma/client';

const prisma = new PrismaClient();

const pretestItems = [
  {
    test_version: 'v1',
    domain: 'aritmetica_y_numeros',
    competency: 'proporcionalidad_simple',
    stem: 'Si 3 cuadernos cuestan S/ 18, ¿cuánto cuestan 5 cuadernos al mismo precio?',
    options: [
      { key: 'A', label: 'S/ 26' },
      { key: 'B', label: 'S/ 28' },
      { key: 'C', label: 'S/ 30' },
      { key: 'D', label: 'S/ 32' },
    ],
    correct_key: 'C',
  },
  {
    test_version: 'v1',
    domain: 'aritmetica_y_numeros',
    competency: 'jerarquia_operaciones',
    stem: 'Calcula: 72 ÷ 8 + 5 × 3.',
    options: [
      { key: 'A', label: '24' },
      { key: 'B', label: '27' },
      { key: 'C', label: '33' },
      { key: 'D', label: '39' },
    ],
    correct_key: 'B',
  },
  {
    test_version: 'v1',
    domain: 'aritmetica_y_numeros',
    competency: 'mcm',
    stem: '¿Cuál es el mínimo común múltiplo (MCM) de 6 y 8?',
    options: [
      { key: 'A', label: '12' },
      { key: 'B', label: '16' },
      { key: 'C', label: '18' },
      { key: 'D', label: '24' },
    ],
    correct_key: 'D',
  },
  {
    test_version: 'v1',
    domain: 'aritmetica_y_numeros',
    competency: 'operaciones_enteros',
    stem: 'Calcula: 15 + 28 - 9.',
    options: [
      { key: 'A', label: '36' },
      { key: 'B', label: '34' },
      { key: 'C', label: '32' },
      { key: 'D', label: '30' },
    ],
    correct_key: 'B',
  },
  {
    test_version: 'v1',
    domain: 'aritmetica_y_numeros',
    competency: 'valor_absoluto',
    stem: '¿Cuál es el valor absoluto de −27?',
    options: [
      { key: 'A', label: '−27' },
      { key: 'B', label: '0' },
      { key: 'C', label: '27' },
      { key: 'D', label: '30' },
    ],
    correct_key: 'C',
  },
  {
    test_version: 'v1',
    domain: 'aritmetica_y_numeros',
    competency: 'fracciones',
    stem: 'Convierte 0,75 a fracción irreductible.',
    options: [
      { key: 'A', label: '1/2' },
      { key: 'B', label: '2/3' },
      { key: 'C', label: '3/4' },
      { key: 'D', label: '4/5' },
    ],
    correct_key: 'C',
  },
  {
    test_version: 'v1',
    domain: 'proporciones_porcentajes',
    competency: 'variacion_porcentual',
    stem: 'Un precio sube 20% y luego baja 20%. Respecto al precio inicial, el resultado es:',
    options: [
      { key: 'A', label: 'Igual' },
      { key: 'B', label: '4% más' },
      { key: 'C', label: '4% menos' },
      { key: 'D', label: '20% menos' },
    ],
    correct_key: 'C',
  },
  {
    test_version: 'v1',
    domain: 'proporciones_porcentajes',
    competency: 'razones',
    stem: 'Una receta usa la razón 2:5 (sal:harina). Si usas 20 g de sal, ¿cuánta harina necesitas?',
    options: [
      { key: 'A', label: '40 g' },
      { key: 'B', label: '50 g' },
      { key: 'C', label: '60 g' },
      { key: 'D', label: '80 g' },
    ],
    correct_key: 'B',
  },
  {
    test_version: 'v1',
    domain: 'proporciones_porcentajes',
    competency: 'descuento',
    stem: 'Un artículo de S/ 150 tiene 15% de descuento. ¿Cuánto pagarás?',
    options: [
      { key: 'A', label: 'S/ 127.50' },
      { key: 'B', label: 'S/ 130.00' },
      { key: 'C', label: 'S/ 135.00' },
      { key: 'D', label: 'S/ 120.00' },
    ],
    correct_key: 'A',
  },
  {
    test_version: 'v1',
    domain: 'proporciones_porcentajes',
    competency: 'regla_de_tres',
    stem: 'Si 4 litros de pintura cubren 18 m^2, ¿cuántos litros necesitas para 45 m^2?',
    options: [
      { key: 'A', label: '8' },
      { key: 'B', label: '9' },
      { key: 'C', label: '10' },
      { key: 'D', label: '12' },
    ],
    correct_key: 'C',
  },
  {
    test_version: 'v1',
    domain: 'proporciones_porcentajes',
    competency: 'incremento_porcentual',
    stem: 'Un salario de S/ 1 200 aumenta 12%. ¿Cuál es el nuevo salario?',
    options: [
      { key: 'A', label: 'S/ 1 296' },
      { key: 'B', label: 'S/ 1 320' },
      { key: 'C', label: 'S/ 1 344' },
      { key: 'D', label: 'S/ 1 360' },
    ],
    correct_key: 'C',
  },
  {
    test_version: 'v1',
    domain: 'proporciones_porcentajes',
    competency: 'mezclas',
    stem: 'Para preparar jugo se mezcla la razón 3:2 (agua:concentrado). Si usas 750 ml de agua, ¿cuánto concentrado necesitas?',
    options: [
      { key: 'A', label: '400 ml' },
      { key: 'B', label: '450 ml' },
      { key: 'C', label: '500 ml' },
      { key: 'D', label: '600 ml' },
    ],
    correct_key: 'C',
  },
  {
    test_version: 'v1',
    domain: 'algebra_basica',
    competency: 'simplificacion',
    stem: 'Simplifica: 3x + 2x - 5.',
    options: [
      { key: 'A', label: '5x - 5' },
      { key: 'B', label: '6x - 5' },
      { key: 'C', label: '3x - 5' },
      { key: 'D', label: '5x + 5' },
    ],
    correct_key: 'A',
  },
  {
    test_version: 'v1',
    domain: 'algebra_basica',
    competency: 'ecuaciones_lineales',
    stem: 'Resuelve: 2x - 7 = 9.',
    options: [
      { key: 'A', label: '1' },
      { key: 'B', label: '6' },
      { key: 'C', label: '8' },
      { key: 'D', label: '16' },
    ],
    correct_key: 'C',
  },
  {
    test_version: 'v1',
    domain: 'algebra_basica',
    competency: 'evaluacion_expresiones',
    stem: 'Si y = 3x + 2 y x = 4, ¿cuál es el valor de y?',
    options: [
      { key: 'A', label: '10' },
      { key: 'B', label: '12' },
      { key: 'C', label: '14' },
      { key: 'D', label: '20' },
    ],
    correct_key: 'C',
  },
  {
    test_version: 'v1',
    domain: 'algebra_basica',
    competency: 'factorizacion',
    stem: 'Factoriza 6x + 9.',
    options: [
      { key: 'A', label: '3(2x + 3)' },
      { key: 'B', label: '6(x + 1.5)' },
      { key: 'C', label: '3x(2 + 3)' },
      { key: 'D', label: 'No se puede factorizar' },
    ],
    correct_key: 'A',
  },
  {
    test_version: 'v1',
    domain: 'algebra_basica',
    competency: 'ecuaciones_lineales',
    stem: 'Resuelve: 4(x - 2) = 3x + 6.',
    options: [
      { key: 'A', label: '4' },
      { key: 'B', label: '10' },
      { key: 'C', label: '12' },
      { key: 'D', label: '14' },
    ],
    correct_key: 'D',
  },
  {
    test_version: 'v1',
    domain: 'algebra_basica',
    competency: 'evaluacion_expresiones',
    stem: 'Evalúa 2a^2 - 3a cuando a = -2.',
    options: [
      { key: 'A', label: '-2' },
      { key: 'B', label: '2' },
      { key: 'C', label: '14' },
      { key: 'D', label: '18' },
    ],
    correct_key: 'C',
  },
  {
    test_version: 'v1',
    domain: 'resolucion_problemas',
    competency: 'cuotas',
    stem: 'Un celular cuesta S/ 900 y se paga en 6 cuotas iguales. ¿Cuánto es cada cuota mensual?',
    options: [
      { key: 'A', label: 'S/ 120' },
      { key: 'B', label: 'S/ 130' },
      { key: 'C', label: 'S/ 140' },
      { key: 'D', label: 'S/ 150' },
    ],
    correct_key: 'D',
  },
  {
    test_version: 'v1',
    domain: 'resolucion_problemas',
    competency: 'variacion_porcentual',
    stem: 'Una tienda aumenta 10% sus ventas de 200 unidades. ¿Cuántas unidades vende ahora?',
    options: [
      { key: 'A', label: '210' },
      { key: 'B', label: '220' },
      { key: 'C', label: '205' },
      { key: 'D', label: '215' },
    ],
    correct_key: 'A',
  },
  {
    test_version: 'v1',
    domain: 'resolucion_problemas',
    competency: 'progreso_trabajo',
    stem: 'Si un trabajador completa 3/4 de una tarea en 6 horas, ¿cuántas horas necesita para completar toda la tarea?',
    options: [
      { key: 'A', label: '7.5' },
      { key: 'B', label: '8' },
      { key: 'C', label: '6.5' },
      { key: 'D', label: '9' },
    ],
    correct_key: 'A',
  },
  {
    test_version: 'v1',
    domain: 'resolucion_problemas',
    competency: 'velocidad_media',
    stem: 'Un tren recorre 240 km en 3 horas y 20 minutos. ¿Cuál es su velocidad promedio?',
    options: [
      { key: 'A', label: '64 km/h' },
      { key: 'B', label: '70 km/h' },
      { key: 'C', label: '72 km/h' },
      { key: 'D', label: '75 km/h' },
    ],
    correct_key: 'C',
  },
  {
    test_version: 'v1',
    domain: 'resolucion_problemas',
    competency: 'proporciones',
    stem: 'Para una reunión se compran 48 refrescos y se consumen 5/8 del total. ¿Cuántos refrescos quedan?',
    options: [
      { key: 'A', label: '12' },
      { key: 'B', label: '16' },
      { key: 'C', label: '18' },
      { key: 'D', label: '20' },
    ],
    correct_key: 'C',
  },
  {
    test_version: 'v1',
    domain: 'resolucion_problemas',
    competency: 'reparto_proporcional',
    stem: 'Una cuenta de S/ 540 se divide entre tres personas en proporción 2:3:5. ¿Cuánto debe pagar la persona con razón 3?',
    options: [
      { key: 'A', label: 'S/ 90' },
      { key: 'B', label: 'S/ 126' },
      { key: 'C', label: 'S/ 162' },
      { key: 'D', label: 'S/ 180' },
    ],
    correct_key: 'C',
  },
];

const posttestItems = [
  {
    test_version: 'exit_v1',
    domain: 'aritmetica_y_numeros',
    competency: 'proporcionalidad_simple',
    stem: 'Si 4 libros cuestan S/ 56, ¿cuánto cuestan 7 libros al mismo precio?',
    options: [
      { key: 'A', label: 'S/ 84' },
      { key: 'B', label: 'S/ 90' },
      { key: 'C', label: 'S/ 98' },
      { key: 'D', label: 'S/ 102' },
    ],
    correct_key: 'C',
  },
  {
    test_version: 'exit_v1',
    domain: 'aritmetica_y_numeros',
    competency: 'jerarquia_operaciones',
    stem: 'Calcula: 96 ÷ 12 + 4 × 7.',
    options: [
      { key: 'A', label: '28' },
      { key: 'B', label: '32' },
      { key: 'C', label: '36' },
      { key: 'D', label: '40' },
    ],
    correct_key: 'C',
  },
  {
    test_version: 'exit_v1',
    domain: 'aritmetica_y_numeros',
    competency: 'mcd',
    stem: '¿Cuál es el máximo común divisor (MCD) de 48 y 30?',
    options: [
      { key: 'A', label: '3' },
      { key: 'B', label: '6' },
      { key: 'C', label: '12' },
      { key: 'D', label: '18' },
    ],
    correct_key: 'B',
  },
  {
    test_version: 'exit_v1',
    domain: 'aritmetica_y_numeros',
    competency: 'operaciones_enteros',
    stem: 'Calcula: 215 - 87 + 46.',
    options: [
      { key: 'A', label: '164' },
      { key: 'B', label: '170' },
      { key: 'C', label: '174' },
      { key: 'D', label: '182' },
    ],
    correct_key: 'C',
  },
  {
    test_version: 'exit_v1',
    domain: 'aritmetica_y_numeros',
    competency: 'potencias',
    stem: '¿Cuál es el cuadrado de 14?',
    options: [
      { key: 'A', label: '168' },
      { key: 'B', label: '182' },
      { key: 'C', label: '196' },
      { key: 'D', label: '210' },
    ],
    correct_key: 'C',
  },
  {
    test_version: 'exit_v1',
    domain: 'aritmetica_y_numeros',
    competency: 'fracciones',
    stem: 'Convierte 1,25 a fracción irreductible.',
    options: [
      { key: 'A', label: '4/5' },
      { key: 'B', label: '5/4' },
      { key: 'C', label: '3/2' },
      { key: 'D', label: '6/5' },
    ],
    correct_key: 'B',
  },
  {
    test_version: 'exit_v1',
    domain: 'proporciones_porcentajes',
    competency: 'variacion_porcentual',
    stem: 'Un precio sube 25% y luego baja 25%. Respecto al precio inicial, el resultado es:',
    options: [
      { key: 'A', label: 'Sin cambio' },
      { key: 'B', label: '6.25% más' },
      { key: 'C', label: '6.25% menos' },
      { key: 'D', label: '25% menos' },
    ],
    correct_key: 'C',
  },
  {
    test_version: 'exit_v1',
    domain: 'proporciones_porcentajes',
    competency: 'razones',
    stem: 'Una mezcla usa la razón 4:9 (componente A:componente B). Si usas 32 g del componente A, ¿cuántos gramos del componente B necesitas?',
    options: [
      { key: 'A', label: '60 g' },
      { key: 'B', label: '68 g' },
      { key: 'C', label: '72 g' },
      { key: 'D', label: '80 g' },
    ],
    correct_key: 'C',
  },
  {
    test_version: 'exit_v1',
    domain: 'proporciones_porcentajes',
    competency: 'descuento',
    stem: 'Un artículo cuesta S/ 280 y tiene 18% de descuento. ¿Cuál es el precio final?',
    options: [
      { key: 'A', label: 'S/ 224.00' },
      { key: 'B', label: 'S/ 229.60' },
      { key: 'C', label: 'S/ 238.00' },
      { key: 'D', label: 'S/ 244.80' },
    ],
    correct_key: 'B',
  },
  {
    test_version: 'exit_v1',
    domain: 'proporciones_porcentajes',
    competency: 'regla_de_tres',
    stem: 'Si 5 litros de fertilizante cubren 30 m^2, ¿cuántos litros necesitas para 48 m^2?',
    options: [
      { key: 'A', label: '6' },
      { key: 'B', label: '7' },
      { key: 'C', label: '8' },
      { key: 'D', label: '9' },
    ],
    correct_key: 'C',
  },
  {
    test_version: 'exit_v1',
    domain: 'proporciones_porcentajes',
    competency: 'incremento_porcentual',
    stem: 'Un salario de S/ 1 500 aumenta 15%. ¿Cuál es el nuevo salario?',
    options: [
      { key: 'A', label: 'S/ 1 620' },
      { key: 'B', label: 'S/ 1 650' },
      { key: 'C', label: 'S/ 1 725' },
      { key: 'D', label: 'S/ 1 785' },
    ],
    correct_key: 'C',
  },
  {
    test_version: 'exit_v1',
    domain: 'proporciones_porcentajes',
    competency: 'mezclas',
    stem: 'Para preparar 1.2 litros de jugo en proporción 2:1 (agua:concentrado), ¿cuánto concentrado necesitas?',
    options: [
      { key: 'A', label: '0.3 L' },
      { key: 'B', label: '0.4 L' },
      { key: 'C', label: '0.5 L' },
      { key: 'D', label: '0.6 L' },
    ],
    correct_key: 'B',
  },
  {
    test_version: 'exit_v1',
    domain: 'algebra_basica',
    competency: 'simplificacion',
    stem: 'Simplifica: 4y - 2y + 10.',
    options: [
      { key: 'A', label: '2y + 10' },
      { key: 'B', label: '2y - 10' },
      { key: 'C', label: '4y + 10' },
      { key: 'D', label: '6y + 10' },
    ],
    correct_key: 'A',
  },
  {
    test_version: 'exit_v1',
    domain: 'algebra_basica',
    competency: 'ecuaciones_lineales',
    stem: 'Resuelve: 3x + 4 = 25.',
    options: [
      { key: 'A', label: '5' },
      { key: 'B', label: '7' },
      { key: 'C', label: '9' },
      { key: 'D', label: '11' },
    ],
    correct_key: 'B',
  },
  {
    test_version: 'exit_v1',
    domain: 'algebra_basica',
    competency: 'evaluacion_expresiones',
    stem: 'Si f(x) = 5 - 2x y x = -3, ¿cuál es el valor de f(x)?',
    options: [
      { key: 'A', label: '-1' },
      { key: 'B', label: '5' },
      { key: 'C', label: '11' },
      { key: 'D', label: '17' },
    ],
    correct_key: 'C',
  },
  {
    test_version: 'exit_v1',
    domain: 'algebra_basica',
    competency: 'factorizacion',
    stem: 'Factoriza 12x - 18.',
    options: [
      { key: 'A', label: '6(2x - 3)' },
      { key: 'B', label: '3(4x - 6)' },
      { key: 'C', label: '2(6x - 9)' },
      { key: 'D', label: 'No se puede factorizar' },
    ],
    correct_key: 'A',
  },
  {
    test_version: 'exit_v1',
    domain: 'algebra_basica',
    competency: 'ecuaciones_lineales',
    stem: 'Resuelve: 5(x - 1) = 2x + 7.',
    options: [
      { key: 'A', label: '3' },
      { key: 'B', label: '4' },
      { key: 'C', label: '5' },
      { key: 'D', label: '6' },
    ],
    correct_key: 'B',
  },
  {
    test_version: 'exit_v1',
    domain: 'algebra_basica',
    competency: 'evaluacion_expresiones',
    stem: 'Evalúa x^2 - 4x + 3 cuando x = 5.',
    options: [
      { key: 'A', label: '6' },
      { key: 'B', label: '8' },
      { key: 'C', label: '9' },
      { key: 'D', label: '11' },
    ],
    correct_key: 'B',
  },
  {
    test_version: 'exit_v1',
    domain: 'resolucion_problemas',
    competency: 'cuotas',
    stem: 'Una laptop cuesta S/ 2 400 y se paga en 8 cuotas iguales. ¿Cuánto es cada cuota?',
    options: [
      { key: 'A', label: 'S/ 260' },
      { key: 'B', label: 'S/ 280' },
      { key: 'C', label: 'S/ 300' },
      { key: 'D', label: 'S/ 320' },
    ],
    correct_key: 'C',
  },
  {
    test_version: 'exit_v1',
    domain: 'resolucion_problemas',
    competency: 'variacion_porcentual',
    stem: 'Las ventas pasan de 350 unidades a 420 unidades. ¿Cuál es el porcentaje de incremento?',
    options: [
      { key: 'A', label: '15%' },
      { key: 'B', label: '18%' },
      { key: 'C', label: '20%' },
      { key: 'D', label: '24%' },
    ],
    correct_key: 'C',
  },
  {
    test_version: 'exit_v1',
    domain: 'resolucion_problemas',
    competency: 'progreso_trabajo',
    stem: 'Un obrero completa 2/5 de una tarea en 4 horas. ¿Cuánto tiempo total necesita para completarla?',
    options: [
      { key: 'A', label: '6 horas' },
      { key: 'B', label: '8 horas' },
      { key: 'C', label: '10 horas' },
      { key: 'D', label: '12 horas' },
    ],
    correct_key: 'C',
  },
  {
    test_version: 'exit_v1',
    domain: 'resolucion_problemas',
    competency: 'velocidad_media',
    stem: 'Un auto recorre 180 km en 2 horas y 15 minutos. ¿Cuál es su velocidad promedio?',
    options: [
      { key: 'A', label: '72 km/h' },
      { key: 'B', label: '75 km/h' },
      { key: 'C', label: '78 km/h' },
      { key: 'D', label: '80 km/h' },
    ],
    correct_key: 'D',
  },
  {
    test_version: 'exit_v1',
    domain: 'resolucion_problemas',
    competency: 'proporciones',
    stem: 'En una receta se requieren 2.4 kg de harina para 3 tortas. ¿Cuánta harina necesitas para 5 tortas?',
    options: [
      { key: 'A', label: '3 kg' },
      { key: 'B', label: '3.6 kg' },
      { key: 'C', label: '4 kg' },
      { key: 'D', label: '4.4 kg' },
    ],
    correct_key: 'C',
  },
  {
    test_version: 'exit_v1',
    domain: 'resolucion_problemas',
    competency: 'reparto_proporcional',
    stem: 'Una deuda de S/ 960 se reparte en proporción 3:4:5. ¿Cuánto paga la persona con razón 4?',
    options: [
      { key: 'A', label: 'S/ 240' },
      { key: 'B', label: 'S/ 300' },
      { key: 'C', label: 'S/ 320' },
      { key: 'D', label: 'S/ 360' },
    ],
    correct_key: 'C',
  },
];

const tamItems = [
  {
    instrument: SurveyInstrument.tam,
    subscale: 'utilidad',
    version: 'v1',
    prompt: 'Usar la plataforma me ayuda a estudiar matemáticas con mayor eficacia.',
    sort_order: 1,
  },
  {
    instrument: SurveyInstrument.tam,
    subscale: 'utilidad',
    version: 'v1',
    prompt: 'La plataforma mejora mi rendimiento en comparación con estudiar solo.',
    sort_order: 2,
  },
  {
    instrument: SurveyInstrument.tam,
    subscale: 'utilidad',
    version: 'v1',
    prompt: 'La plataforma es útil para alcanzar mis metas de aprendizaje.',
    sort_order: 3,
  },
  {
    instrument: SurveyInstrument.tam,
    subscale: 'facilidad',
    version: 'v1',
    prompt: 'Aprender a usar la plataforma fue sencillo para mí.',
    sort_order: 4,
  },
  {
    instrument: SurveyInstrument.tam,
    subscale: 'facilidad',
    version: 'v1',
    prompt: 'Interactuar con la plataforma no requiere mucho esfuerzo mental.',
    sort_order: 5,
  },
  {
    instrument: SurveyInstrument.tam,
    subscale: 'facilidad',
    version: 'v1',
    prompt: 'Encuentro fácil navegar entre actividades y evaluaciones.',
    sort_order: 6,
  },
  {
    instrument: SurveyInstrument.tam,
    subscale: 'intencion',
    version: 'v1',
    prompt: 'Continuaría usando esta plataforma para aprender matemáticas.',
    sort_order: 7,
  },
  {
    instrument: SurveyInstrument.tam,
    subscale: 'intencion',
    version: 'v1',
    prompt: 'Estoy satisfecho/a con la experiencia general.',
    sort_order: 8,
  },
];

const motivacionItems = [
  {
    instrument: SurveyInstrument.motivacion,
    subscale: 'motivacion',
    version: 'v1',
    prompt: 'Estudiar matemáticas aquí me resulta interesante.',
    sort_order: 1,
  },
  {
    instrument: SurveyInstrument.motivacion,
    subscale: 'motivacion',
    version: 'v1',
    prompt: 'Considero útiles para mi vida diaria las actividades propuestas.',
    sort_order: 2,
  },
  {
    instrument: SurveyInstrument.motivacion,
    subscale: 'motivacion',
    version: 'v1',
    prompt: 'Me esfuerzo por terminar los ejercicios aunque sean difíciles.',
    sort_order: 3,
  },
  {
    instrument: SurveyInstrument.motivacion,
    subscale: 'motivacion',
    version: 'v1',
    prompt: 'Cuando fallo, intento nuevamente hasta resolverlos.',
    sort_order: 4,
  },
  {
    instrument: SurveyInstrument.motivacion,
    subscale: 'motivacion',
    version: 'v1',
    prompt: 'Las metas de la plataforma me mantienen enfocado/a.',
    sort_order: 5,
  },
  {
    instrument: SurveyInstrument.motivacion,
    subscale: 'motivacion',
    version: 'v1',
    prompt: 'Me siento más seguro/a para enfrentar nuevos problemas.',
    sort_order: 6,
  },
];

const autonomiaItems = [
  {
    instrument: SurveyInstrument.autonomia,
    subscale: 'autonomia',
    version: 'v1',
    prompt: 'Planifico cuándo y cuánto estudiaré cada semana.',
    sort_order: 1,
  },
  {
    instrument: SurveyInstrument.autonomia,
    subscale: 'autonomia',
    version: 'v1',
    prompt: 'Reviso si comprendí lo estudiado y ajusto mi plan.',
    sort_order: 2,
  },
  {
    instrument: SurveyInstrument.autonomia,
    subscale: 'autonomia',
    version: 'v1',
    prompt: 'Tomo notas o registro de errores comunes para mejorar.',
    sort_order: 3,
  },
  {
    instrument: SurveyInstrument.autonomia,
    subscale: 'autonomia',
    version: 'v1',
    prompt: 'Pido retroalimentación o pistas solo cuando lo necesito.',
    sort_order: 4,
  },
  {
    instrument: SurveyInstrument.autonomia,
    subscale: 'autonomia',
    version: 'v1',
    prompt: 'Controlo distracciones mientras practico.',
    sort_order: 5,
  },
  {
    instrument: SurveyInstrument.autonomia,
    subscale: 'autonomia',
    version: 'v1',
    prompt: 'Al finalizar, evalúo qué estrategias me funcionaron.',
    sort_order: 6,
  },
];

async function run() {
  await prisma.assessmentResponse.deleteMany({});
  await prisma.assessment.deleteMany({});
  await prisma.assessmentItem.deleteMany({});
  await prisma.surveyResponse.deleteMany({});
  await prisma.surveySubmission.deleteMany({});
  await prisma.surveyItem.deleteMany({});

  await prisma.assessmentItem.createMany({
    data: [...pretestItems, ...posttestItems],
    skipDuplicates: true,
  });

  await prisma.surveyItem.createMany({
    data: [...tamItems, ...motivacionItems, ...autonomiaItems],
    skipDuplicates: true,
  });

  console.log('Seed data inserted');
}

run()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
